#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

uptime - Plugin to measure uptime.

=head1 NOTES

Especially the average and max values on the bigger graphs (yearly) can be interesting.

=head1 AUTHOR

Contributed by Nicolas Salles

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

# . "$MUNIN_LIBDIR/plugins/plugin.sh"

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then

        echo 'graph_title Homeassistant DB size'
        echo 'graph_args --base 1000 -l 0 '
        echo 'graph_scale no'
        echo 'graph_vlabel Database size'
        echo 'graph_category custom'
        echo 'hass.label hass db'
        echo 'hass.draw AREA'
        exit 0
fi

file=home-assistant_v2.db
dir=/home/ubuntu/homeassistant_config

echo -n "hass.value "
echo $(du -cks "${dir}/${file}" | grep total | cut -f 1)
