esphome:
  name: $name
  platform: $platform
  board: $board

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  use_address: $name.middle.earth
  ssid: "ironforge"
  password: !secret ap_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$name Fallback Hotspot"
    password: !secret fallback_ap_password

mqtt:
  broker: pine64.middle.earth
  log_topic: log/$name

web_server:

captive_portal:
