substitutions:
  name: d1_mini
  platform: ESP8266
  board: d1_mini
  pin: D4
  # have to invert here and connect the wrong way around.. essentially making the switch pull up instead of down
  # I think the pull down resistor was not pulling the pin low enough, so it was always on. Inverted means it is considered on when low
  inverted: 'true'

<<: !include base.yaml

binary_sensor:
  - <<: !include light_button.yaml
