substitutions:
  name: d1_mini
  friendly_name: Hall
  night_light_pin: D3
  # have to invert here and connect the wrong way around.. essentially making the switch pull up instead of down
  # I think the pull down resistor was not pulling the pin low enough, so it was always on. Inverted means it is considered on when low
  inverted: 'true'
  dht_pin: D2

esp8266:
  board: d1_mini

packages:
  base: !include base.yaml
  night_light: !include night_light.yaml
  dht: !include dht_temperature.yaml

switch:
  - platform: gpio
    pin:
      number: D4
      inverted: false
    name: Ground pin
    restore_mode: ALWAYS_OFF

