platform: gpio
pin:
  number: $pin
  mode:
    input: true
    # pulldown: true
  # have to invert here and connect the wrong way around.. essentially making the switch pull up instead of down
  # I think the pull down resistor was not pulling the pin low enough, so it was always on. Inverted means it is considered on when low
  inverted: $inverted
name: "Light button - $name"
on_click:
  - min_length: 50ms
    max_length: 500ms
    then:
      - logger.log: "Button Pressed"
      - mqtt.publish: 
          topic: trigger/$name/button_pressed
          payload: 'on'
  - min_length: 750ms
    max_length: 2000ms
    then:          
      - logger.log: "Button Long pressed"
      - mqtt.publish: 
          topic: trigger/$name/button_long_pressed
          payload: 'on'
