substitutions:
  name: nodemcu
  light_button_pin: D7
  inverted: true
  friendly_name: Bed
  dht_pin: D2

esp8266:
  board: nodemcu

packages:
  - !include base.yaml
  - !include light_button.yaml
  - !include dht_temperature.yaml

sensor:
  - platform: ccs811
    eco2:
      name: "eCO2 Value"
    tvoc:
      name: "Total Volatile Organic Compound"
    address: 0x5A
    update_interval: 60s

i2c:
  scl: D5
  sda: D6
