#{{ansible_managed}}
schedules:
  - tasks: get_subtitles
    interval:
      hours: 1
  - tasks: [showrss-dload, move-to-archive]
    interval:
      hours: 4
web_server:
  port: 5050
  base_url: /flexget
templates:
  notify_pushbullet:
    notify:
      entries:
        title: "{{ '{{task}}'}}"
        message: "{{ '{{series_name}} - {{series_id}}' }}"
        via:
          - pushbullet:
              api_key: {{pushbullet_access_token}}
  deluge-tv-download:
    convert_magnet: yes
    thetvdb_lookup: yes
    deluge:
      movedone: {{'/media/ubuntu/Archive/Torrent/TV Shows/{{series_name}}/'}}
      main_file_only: yes
      ratio: 0.1
      removeatratio: yes
      magnetization_timeout: 100
      keep_subs: yes
      content_filename: >
        {{'{{ tvdb_series_name  }} - S{{ series_season|pad(2) }}E{{ series_episode|pad(2) }} - {{ tvdb_ep_name |default("") }}'}}
tasks:
  showrss-dload:
    rss:
      url: {{rss_url}}
    manipulate:
      title:
        replace:
          regexp: Riverdale.US
          format: Riverdale
    all_series:
      propers: 12 hours
    make_html:
      file: ~/downloaded.html
    template:
      - deluge-tv-download
      - notify_pushbullet

  # http://discuss.flexget.com/t/cleanup-on-move-deletes-top-level-folder/491/3
  #problems a) season was wrong b) didnt rename at all..

  get_subtitles:
    manual: yes
    filesystem:
      path:
        - /media/ubuntu/Archive/Torrent/TV Shows/
      regexp: '.*\.(avi|mkv|mp4|m4v|mpg|wmv)$'  # only include filenames with these extensions
      recursive: yes
    accept_all: yes
    seen: local                     # seen shouldn't interfer with anything outside this subtitles task
    template: notify_pushbullet
    subliminal:
      languages:
        - eng
      providers: [opensubtitles]
      authentication:
        opensubtitles:
          username: {{opensubtitles_username}}
          password: {{opensubtitles_password}}

  move-to-archive:
    template: notify_pushbullet
    no_entries_ok: yes
    accept_all: yes
    metainfo_series: yes
    seen: local # also from below link, but makes sense i think, so that downloaded files dont get rejected.. maybe redundant with accept_all..
    require_field: series_name # otherwise i think some entries have http://discuss.flexget.com/t/copy-plugin-says-series-name-is-undefined/1185/10 - on elementary specifically
    configure_series:
      settings:
        parse_only: yes
        identified_by: ep
      from:
        filesystem:
          path: /media/ubuntu/Archive/Torrent/TV Shows/
    filesystem:
      path: /media/ubuntu/Archive/Torrent/TV Shows/
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4|m4v|mpg|wmv|srt|sub|sbv)$'
    # Ignore samples
    regexp:
      reject:
        - sample
    pathscrub: windows
    manipulate:
    - filename:
        replace:
          regexp: :|\?
          format: ''
    move:
      to: {{'/media/ubuntu/Archive/TV Shows/{{series_name}}/Season {{series_season}}/'}}
      clean_source: 50
    make_html:
      file: ~/moved.html
    kodi_library:
      action: scan
      category: video
      url: http://192.168.1.244
      port: 8080

  search-missing:
    manual: yes
    discover:
      what:
        - next_series_episodes:
            from_start: yes
            backfill: yes
      from:
        - search_rss: https://www.skytorrents.in/rss/all/ad/1/{{ '{{ search_term }}' }}
    torrent_alive: 10
    quality: 480p-720p
    exists_series: {{'/media/ubuntu/Archive/TV Shows/{{series_name}}'}}
    domain_delay:
      skytorrents.in: 2 seconds
    series:
      settings:
        shows:
          identified_by: ep
          tracking: backfill
      shows:
        - The Walking Dead
        - Elementary
    template:
      - deluge-tv-download
      - notify_pushbullet

  #https://flexget.com/Cookbook/Series/SeedDB
  seed_series_db:
    # The find plugin will find all of your existing episodes
    filesystem:
      regexp: .*(avi|mkv|mp4|m4v|mpg|wmv|srt|sub|sbv)$
      path:
        - /media/ubuntu/Archive/TV Shows/The Walking Dead
        - /media/ubuntu/Archive/TV Shows/Elementary
      recursive: yes
    # We use the manual plugin so that this task only runs when explicitly called
    manual: yes

