#{{ansible_managed}}
#prettier-ignore
schedules:
  - tasks: [showrss-dload]
    interval:
      hours: 1
  - tasks: [move-to-chest, get_subs]
    interval:
      hours: 4
  - tasks: [trakt_movie_list, movies_search]
    interval:
      hours: 24
web_server:
  port: 5050
  base_url: /flexget
templates:
  subliminal:
    subliminal:
      exact_match: no
      languages:
        - eng
      providers: [opensubtitles,thesubdb,tvsubtitles]
      authentication:
        opensubtitles:
          username: {{opensubtitles_username}}
          password: {{opensubtitles_password}}
  notify_tv:
    notify:
      entries: &notify-entries
        what: accepted
        message: "{{ '[{{task}}] {{series_name}} - {{series_id}}' }}"
        via:
          - telegram:
              bot_token: {{flexget_telegram_bot_token}}
              recipients:
                - username: ktaragorn
  notify_movie:
    imdb_lookup: yes
    notify:
      entries:
        <<: *notify-entries
        message: "{{ '[{{task}}] {{movie_name}} ({{movie_year}})'}}"

  fix_title_filename:
    manipulate:
      - filename:
          replace:
            regexp: :|\?
            format: ''
# trying as per suggestion in https://discuss.flexget.com/t/manipulate-help-or-other-solutions/4350/2?u=ktaragorn
  fix_riverdale_detection:
    series:
      - Riverdale:
          alternate_name: Riverdale US
      - Blackish:
          # sadly doesnt work
          set:
            tvdb_id: 281511
  configure_series_from_downloaded:
    require_field: series_name # otherwise i think some entries have http://discuss.flexget.com/t/copy-plugin-says-series-name-is-undefined/1185/10 - on elementary specifically
    metainfo_series: yes
    configure_series:
      settings:
        parse_only: yes
        identified_by: ep
      from:
        filesystem:
          path: /media/ubuntu/Chest/Torrent/TV Shows/
  work_on_downloaded_files:
    filesystem:
      path: /media/ubuntu/Chest/Torrent/TV Shows/
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4|m4v|mpg|wmv)$'
  kodi_scan:
    kodi_library:
      action: scan
      category: video
      url: http://{{kodi_main_host}}
      port: {{kodi_main_host_port}}
      username: {{kodi_username}}
      password: {{kodi_password}}
  deluge_download:
    convert_magnet: yes
    deluge:
      path: /media/ubuntu/Chest/Torrent/
      main_file_only: yes
      ratio: 0.1
      remove_at_ratio: yes
      magnetization_timeout: 100
      keep_subs: yes
  deluge_tv:
    thetvdb_lookup: yes
    deluge:
      move_completed_path: {{'/media/ubuntu/Chest/Torrent/TV Shows/{{series_name}}/'}}
      content_filename: >
        {{'{{ series_name  }} - S{{ series_season|pad(2) }}E{{ series_episode|pad(2) }} - {{ tvdb_ep_name |default("") }}'}}
tasks:
  showrss-dload:
    rss:
      url: {{rss_url}}
    all_series:
      propers: 1 hour
    template:
      - fix_riverdale_detection
      - deluge_download
      - deluge_tv
      - notify_tv

  showrss-dload-adhoc:
    rss:
      url: file:///tmp/adhoc.rss
    manual: yes
    all_series:
      propers: 1 hour
    template:
      - fix_riverdale_detection
      - deluge_download
      - deluge_tv
      - notify_tv

  # http://discuss.flexget.com/t/cleanup-on-move-deletes-top-level-folder/491/3
  #problems a) season was wrong b) didnt rename at all..

  # prerequisite https://flexget.com/Trakt_Authentication
  trakt_movie_list:
    priority: 1
    no_entries_ok: yes
    trakt_list: &trakt_list
      username: {{trakt_username}}
      account: {{trakt_username}}
      list: movies_to_get
      type: movies
    accept_all: yes
    seen: local
    list_add:
      - movie_list: movies_download
    list_remove:
      - trakt_list: *trakt_list
    template:
      - notify_movie

  # task that automatically downloads movies from the movie_list
  movies_search:
    priority: 10 # run after the movie queue fill task
    no_entries_ok: yes
    discover:
      what:
        - movie_list: movies_download
      from:
        - piratebay: yes
      interval: 7 days
    torrent_alive: 3 # Will reject results with less than 3 seeds
    quality: 720p # Make sure no screeners or cams are downloaded
    list_match:
      from:
        - movie_list: movies_download
    convert_magnet: yes
    thetvdb_lookup: yes
    template:
      - deluge_download
      - notify_movie

  # from https://flexget.com/Plugins/List/subtitle_list
  get_subs:
    disable:
      - seen
    all_series:
      parse_only: yes
    no_entries_ok: yes
    subtitle_list:
      list: subtitles
      recursion_depth: 3
    list_match:
      from:
        - subtitle_list:
            list: subtitles
    template:
      - subliminal
      - notify_tv

  move-to-chest:
    template:
      - configure_series_from_downloaded
      - fix_title_filename
      - fix_riverdale_detection
      - notify_tv
      - work_on_downloaded_files
      # - kodi_scan
    no_entries_ok: yes
    accept_all: yes
    #seen: local # also from below link, but makes sense i think, so that downloaded files dont get rejected.. maybe redundant with accept_all..
    disable: # redownloads and propers etc should go through
      - seen
      - retry_failed # fails due to failures in other tasks (subtitles)
      - backlog # kodi scan fails fail to clear backlog, and it repeats.. also we dont need this since we operate on exisiting files only
    thetvdb_lookup: yes
    regexp:
      reject:
        - sample
    pathscrub: windows
    list_add:
      - subtitle_list:
          list: subtitles
          languages:
            - en
    move:
      to: {{'/media/ubuntu/Chest/TV Shows/{{series_name}}/Season {{series_season}}/'}}
      clean_source: 50
      rename: >
        {{'{{ tvdb_series_name  }} - S{{ series_season|pad(2) }}E{{ series_episode|pad(2) }} - {{ tvdb_ep_name |default("") }}'}}
      along:
        extensions:
          - srt
          - sub
          - sbv
