---
- alias: 'Set HA theme for day and night'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "above_horizon" %}
            default
          {% else %}
            BlueNight
          {% endif %}
- alias: Any Entered house
  id: any_enter_house
  trigger:
    platform: state
    entity_id: group.all_people
    to: home
  action:
    - service: script.downstairs_ac
      data:
        mode: cool
    - service: script.notify
      data:
        target: home_enter
        message: Someone entered house. Downstairs AC is on.

- alias: All left home
  id: all_leave_house
  trigger:
    platform: state
    entity_id: group.all_people
    to: not_home
  action:
    - service: script.downstairs_ac
      data:
        mode: "off"
    - service: climate.turn_off
      entity_id: climate.bedroom_ac
    - service: light.turn_off
      entity_id: light.bedroom_light
    - service: input_boolean.turn_off # cleanup, just in case
      data:
        entity_id: input_boolean.we_are_in_bed
    - service: script.notify
      data:
        target: home_enter
        message: All have left the house, Both ACs have been switched off

- alias: Downstairs Button Pressed
  id: button_pressed
  trigger:
    - platform: mqtt
      topic: trigger/nodemcu/button_pressed
  action:
    - service: light.toggle
      entity_id: light.bedroom_light

- alias: Downstairs Button double Pressed
  id: button_double_pressed
  trigger:
    - platform: mqtt
      topic: trigger/nodemcu/button_double_pressed
  action:
    - service: script.downstairs_ac
      data_template:
        mode: >
          {% if is_state("climate.downstairs_ac", "off") %}
            cool
          {% else %}
            off
          {% endif %}

- alias: Downstairs Button long Pressed
  id: button_long_pressed
  trigger:
    - platform: mqtt
      topic: trigger/nodemcu/button_long_pressed
  action:
    - service: input_boolean.toggle
      data:
        entity_id: input_boolean.we_are_going_to_bedroom

- alias: We are going to bed
  id: moved_to_bedroom
  trigger:
    - platform: state
      entity_id: binary_sensor.phone_charging
      to: "on"
    - platform: time
      at: "23:59:00"
    - platform: state
      entity_id: input_boolean.we_are_going_to_bedroom
      to: "on"
  condition:
    - condition: state
      entity_id: group.all_people
      state: home
    # - condition: time
    #   after: '20:00:00'
    - condition: state
      entity_id: input_boolean.we_are_in_bed
      state: "off"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.bedroom_ac
        temperature: 24
        hvac_mode: cool
    - service: climate.set_fan_mode
      data:
        entity_id: climate.bedroom_ac
        fan_mode: lowMedium
    - service: light.turn_off
      entity_id: light.bedroom_light
    # - service: script.toggle_tv
    #   data:
    #     tv_state: "on"
    - service: script.downstairs_ac
      data:
        mode: "off"
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.we_are_in_bed
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.we_are_going_to_bedroom
    - service: script.notify
      data_template:
        target: in_bed
        message: We have come to bed, AC downstairs is off, AC in the bedroom is on, triggered by the {{ trigger.platform }} trigger


- alias: Start Sleep timer
  id: start_sleep_timer
  trigger:
    - platform: webhook
      webhook_id: tv_sleep_timer
  condition:
    - condition: state
      entity_id: input_boolean.we_are_in_bed
      state: "on"
  action:
    - service: timer.cancel
      entity_id: timer.tv_sleep_timer
    - service: script.downstairs_ac
      data:
        mode: "off" # audio feedback
    - service: timer.start
      data:
        entity_id: timer.tv_sleep_timer
        duration: 00:20:00
    - service: script.notify
      data:
        target: sleep_timer
        message: We have come to bed, AC downstairs is off, AC in the bedroom is on

# Home assistant cannot use the same trigger with multiple automations
- alias: Sleep timer triggered
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.tv_sleep_timer
    - platform: webhook
      webhook_id: tv_sleep_timer_trigger
  condition:
    - condition: state
      entity_id: input_boolean.we_are_in_bed
      state: "on"
    - condition: state
      entity_id: timer.tv_sleep_timer
      state: active
  action:
    - service: timer.cancel
      entity_id: timer.tv_sleep_timer
    - service: script.toggle_tv
      data:
        tv_state: "off"
    - service: script.notify
      data:
        target: sleep_timer
        message: Sleep Timer - TV turned off

- alias: We are in bed, increase temperature 1
  id: bedroom_ac_temp_up_1
  trigger:
    - platform: time
      at: "2:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.we_are_in_bed
      state: "on"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.bedroom_ac
        temperature: 24
    - service: climate.set_fan_mode
      data:
        entity_id: climate.bedroom_ac
        fan_mode: night
    - service: script.notify
      data:
        target: in_bed
        message: Bedroom temperature at 24

- alias: We are in bed, increase temperature 2
  id: bedroom_ac_temp_up_2
  trigger:
    - platform: time
      at: "5:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.we_are_in_bed
      state: "on"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.bedroom_ac
        temperature: 25
    - service: script.notify
      data:
        target: in_bed
        message: Bedroom temperature at 25

- alias: We are in bed, set fan mode
  id: bedroom_ac_fan
  trigger:
    - platform: time
      at: "7:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.we_are_in_bed
      state: "on"
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.bedroom_ac
        hvac_mode: fan_only
    - service: climate.set_fan_mode
      data:
        entity_id: climate.bedroom_ac
        fan_mode: lowMedium
    - service: script.notify
      data:
        target: in_bed
        message: Bedroom AC on fan

- alias: We are heading down on workdays
  id: moved_downstairs_work
  trigger:
    - platform: state
      entity_id: binary_sensor.phone_charging
      to: "off"
    - platform: time
      at: "10:00:00"
    - platform: state
      entity_id: input_boolean.we_are_going_to_bedroom
      to: "off"
  condition:
    - condition: time
      after: "07:00:00"
      before: '22:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: group.all_people
      state: home
    - condition: state
      entity_id: input_boolean.we_are_in_bed
      state: "on"
  action: &going_down_actions
    - service: climate.turn_off
      entity_id: climate.bedroom_ac
    # - service: script.downstairs_ac
    #   data:
    #     mode: cool
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.we_are_in_bed
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.we_are_going_to_bedroom
    - service: script.notify
      data_template:
        target: in_bed
        message: We are going downstairs, AC downstairs is on, AC in the bedroom is off, triggered by the {{ trigger.platform }} trigger

- alias: We are heading down on holidays
  id: moved_downstairs_holiday
  trigger:
    - platform: state
      entity_id: binary_sensor.phone_charging
      to: "off"
    - platform: time
      at: "10:00:00"
    - platform: state
      entity_id: input_boolean.we_are_going_to_bedroom
      to: "off"
  condition:
    - condition: time
      after: "07:00:00"
      before: '22:30:00'
      weekday:
        - sun
        - sat
    - condition: state
      entity_id: group.all_people
      state: home
    - condition: state
      entity_id: input_boolean.we_are_in_bed
      state: "on"
  action: *going_down_actions