homeassistant:
  # Name of the location where Home Assistant is running
  name: Gondor
  # Location required to calculate the time the sun rises and sets
  latitude: {{ home_lat }}
  longitude: {{ home_long }}
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: {{ timezone }}
  # Customization file
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config
  # customize_domain:
  #   automation:
  #     hidden: true

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: http://hass.middle.earth
  use_x_forwarded_for: true
  trusted_proxies: 
    - 127.0.0.1
    - ::1

logger:
  default: info
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:
#   # Optional, allows Home Assistant developers to focus on popular components.
#   include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# improvements for SD card from https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/295795
# exclude bad entities consuming too much space
# store for fewer days, write less frequently
recorder:
  purge_keep_days: 5
  commit_interval: 60
  exclude:
    entities:
      - light.bedroom_light_2
      - weather.openweathermap
      - media_player.bedroom_tv
      - number.bedroom_light_effect_speed
      # - sensor.home_assistant_v2_db_size

# Enables a map showing the location of tracked devices
map:

# # Track the sun
sun:

system_health:

# Sensors
# sensor:
# Weather prediction
# - platform: yr

sensor:
  # no yaml no more
  # - platform: filesize
  #   file_paths:
  #     - /config/home-assistant_v2.db
  - platform: time_date
    display_options: 
      - date_time
  # no yaml no more
  # - platform: mqtt
  #   state_topic: state/nodemcu/pir_sensor
  #   name: Bedroom Movement
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /Chest
      #- type: disk_use_percent
      #  arg: /Archive
      - type: memory_use_percent
      - type: load_1m
      - type: processor_use     
      - type: processor_temperature # not supported at current version of hass

  # configured as an integration via UI :(
  # - platform: openweathermap
  #   api_key: {{openweathermap_apikey}}
  #   forecast: 0
  #   monitored_conditions:
  #     - weather
  #     - temperature

# Text to speech
tts:
  - platform: google_translate

# Cloud
# cloud:

# switch:
  # # - platform: broadlink
  #   host: blackbean1
  #   mac: "78:0F:77:50:98:D3"
  #   switches:
  #     # Disabled because of SmartIR?
  #     # bedroom_ac:
  #     #   friendly_name: Aircon
  #     #   # 21C
  #     #   # command_on: JgBQAg0ODw8MEQ0PDBAMAANFcDsMLAwRDBEMEQwsCxEMEQwQCxEMLA0RDCwMLAwSDCsNLAwtDC0MLAwRDBAMLQwQDBEMEAwQDBEMEAwQDRELEAwSDCsMEQwsDBEMEAwRDCwMLQwQDBEMEAwQDRAMEAwRDBAMEAwRDBAMEA0QDBAMEQwQDC0MLAwtDBANLAwRDCwMLQwABHtwOwwsDRAMEAwRDCwMEQwQDBANEAwtDBAMLQwsDRAMLA0sDC0MLQwsDRAMEAwtDBAMEQwQDBANEAwQDBEMEAwQDBEMEAwtDBAMEA0QDBAMLQwQDC0MLQwQDC0MLQwQDC0MLA0sDC0MEAwRDBAMEA0QDBAMEQwsDBEMEAwtDCwNEAwQDAAEfHA6DC0MEAwQDRAMLQwQDBAMEQwQDC0MEAwtDC0MEAwtDCwNLAwtDC0MEAwQDSwMEQwQDBAMEQwQDBANEAwQDBEMEAwQDBEMEAwQDBEMEAwQDRAMLA0QDBAMLQwtDCwNEAwQDBEMLAwRDCwMEQwsDRAMEAwRDBAMEAwRDBAMEQwQDBAMEQwQDBAMEQwQDC0MEAwtDBAMEQwQDBAMEQwQDBEMEAwRDBAMEAwQDBEMEAwQDRAMEAwtDC0MEAwQDBEMEAwRDBAMEAwRDBAMEA0sDC0MEAwRDBAMEAwRDBAMEA0QDBAMEQwQDBAMEQwQDBAMEQwQDBEMDw0RDBEMEAwPDC0MLQwQDBEMEAwQDBEMEAwQDBENDwwRDBAMEAwRDBAMEAwRDCwNLAwRDCwMLQwtDBAMEA0ADQUAAAAAAAAAAA==
  #     #   # 22C
  #     #   # command_on: JgBQAg0QDBAMEQwQDBAMAANFcDsMLA0QDBAMEQwsDBEMEAwQDRAMLQwQDC0MLAwRDCwNLAwtDC0MLA0QDBAMLQwQDAwREAwQDRAMEAwRDBAMEAwQDSwMEQwsDRAMEAwRDCwMLQwPDhAMEAwRDBAMEAwRDBAMEA0QDBAMEQwQDBAMEQwQDC0MLA0sDBEMLAwRDCwMLQwABHxvOwwtDBAMEAwRDCwNEAwQDBEMEAwtDBAMLQ0rDRAMLQwsDSwMLQwtDBAMEAwtDBANEAwQDBEMDw0QDBEMEAwQDBEMEAwtDBAMEQwQDBAMLQwQDSwMLQwQDC0MLQwPDS0MLQwsDC0NDw0QDBAMEQwQDBAMEQwsDRAMEAwtDC0MEAwQDAAEfG87DC0MEAwRDBAMLQwQDQ8NEAwPDS0MEAwtDC0MEAwtDSwMLAwtDC0MEAwRDCwMEQwQDBAMEQwPDRANEAwQDBEMEAwQDBEMEAwQDRAMEAwRDBAMLQwQDBAMLQwtDC0MEAwQDBEMEAwtDCwNEAwtDBAMEA0QDBAMEQwQDBAMEQwQDBAMEQwQDBANEAwQDC0MEAwtDBAMEQwQDBANEAwQDBEMEAwQDBEMEAwQDRAMEAwRDBAMEAwtDC0MEAwQDRAMEAwRDBAMEAwRDBAMEA0sDC0MEAwRDBAMEA0QDBAMEA0QDBAMEQwQDBAMEQwQDBANEAwQDBEMEAwQDBEMEAwQDC0MLQwQDBEMEAwQDBEMEAwQDRAMEAwRDBAMEAwRDBAMEA0QDCwNEAwtDCwMLQwtDBAMEQwADQUAAAAAAAAAAA=
  #     #   # 23C
  #     #   # command_on: JgBSAg0QDBEMEAwQDAADRXA6DC0MEQwQDBELLQwRCxEMEQsRDCwMEQwsDC0MEA0sDC0NLAwsDC0MEQwRDCwMEAwRCxEMEQsQDBEMEAwRDRAMEAwsDRAMLAwRDBAMEAwtDC0MEAwQDBEMEAwRDBAMEAwRDBAMEAwRDBAMEA0QDBELEQ0rDC0MLQwQDC0MEAwtDC0MAAR7cDoNLAwRDBAMEAwtDBANEAwQDBEMLAwRDCwMLQwQDSwMLQwtDCwMLQwQDRAMLQwQDBANEAwRDBANEAwPDBEMEAwQDBENKw0QDQ8MEA0QDC0MEAwQDC0MEA0sDC0MEAwtDC0MLQwsDBEMEAwQDBEMEAwQDSwMEQwQDBAMLQwtDBAMEQwABHtwOgwtDBANEAwQDC0MEAwSDA8MEAwtDBEMLAwtDBANLAwtDCwNLA0sDQ8NEAwsDRAMEAwRDBAMEAwRDBAMEAwQDRAMEQwQDBAMEQwQDBAMEQwQDC0MEAwRDCwMLQwtDBAMEQwQDC0MLAwtDBANLA0QDBAMEAwRDBAMEA0QDBAMEQwQDA8NEQwQDBAMEQwsDRAMLQwQDBAMEQwQDBANEAwQDBEMEAwQDBEMEAwQDBEMEAwQDRAMLQwsDBEMEAwQDRAMEAwRDBAMEAwSDA8MLQwsDRAMEAwRDBAMEAwRDBAMEA0QDBAMEQwQDBAMEQwQDBAMEgwNDhANEAwQDBEMEAwtDCwNDQ8QDBEMEAwQDBEMEAwQDRAMEAwRDBAMEAwRDBAMEAwtDC0MLQwsDC0MLQwQDBEMAAr0CgANBQAAAAAAAA==
  #     #   # 24C
  #     #   command_on: JgBQAg0PDBANEAwQDBEMAANFbzsMLQwPDREMEAwtDBAMEAwRDBAMLQwQDC0MLQwQDC0MLA0sDC0MLQwQDBANLAwRDBAMEAwRDBAMEAwRDBAMEQwQDC0MEAwtDBAMEA0QDC0MLAwRDBAMEA0QDBAMEQwQDBAMEQwQDBANEAwQDBANEAwQDC0MLQwsDRAMLA4NDi0MLAwABHxvOwwtDBAMEQwQDC0MEAwQDRAMEAwtDBAMLQwtDBAMLQwtDCwMLQwtDBAMEQwsDBEMEAwQDRAMEAwQDRAMEAwRDBAMEAwtDBANEAwQDBEMLAwRDCwMEQwQDC0MLQwQDC0MLA0sDC0MEAwQDRAMEA0QDBAMEQwQDBAMEQwsDC0MEA0QDAAEe3A7DCwMEQwQDBANLA0QDBAMEAwRDCwNEAwsDSwMEQwsDC0MLQwtDCwMEQwQDC0MEAwQDRAMEAwRDBAMEAwRDBAMEA0QDBAMEQwQDBAMEQwQDBANLAwQDRAMLQwsDC0MEA0QDBAMEQwQDBAMLQwtDBAMEQwQDBAMEQwQDBAMEQwQDBANEAwQDBEMEAwQDC0MEA0sDBEMEAwQDBEMEAwQDRAMEAwRDBAMEAwRDBAMEAwRDBAMEA0sDC0MEAwRDBAMEAwRDBAMEA0QDBAMEQwsDC0MEA0QDBAMEQwQDBAMEQwQDBANEAwQDBANEAwQDBEMEAwQDBEMEAwQDRAMEAwRDCwMLQwQDRAMEAwQDRAMEAwRDBAMEAwRDBAMEA0QDBAMEA0QDC0MEAwQDBEMEAwQDSwNEAwADQUAAAAAAAAAAA==
  #     #   #25C
  #     #   # command_on: JgBQAg0QDQ8MEQwQDBAMAANGbzsNLAwQDBAMEQwsDRAMEAwRDBAMLQwQDC0NKw0QDCwNLAwtDC0NKw0QDBAMLQwQDBEMEAwQDRAMEAwRDBAMEAwRDCwNEAwsDRAMEAwRDCwMLQ0PDRAMEAwRDBAMEAwRDBAMEA0QDBAMEA0QDBAMEQwQDC0MLA0sDBEMLAwRDCwNLA0ABHtwOgwtDQ8MEA0QDCwNEAwQDBEMEAwtDBAMLQwtDBAMLQwsDSwMLQwtDBAMEA0sDBEMEAwQDBEMEAwQDBEMEAwQDRAMEAwtDBAMEQwQDBAMLQwQDRAMEAwRDCwNLAwQDSwMLQwtDSsMEQwQDBANEAwQDBEMLAwtDC0NLAwQDC0MEAwQDAAEfG87DC0MEAwRDBAMLQwQDBANEAwQDC0MEAwtDC0MEAwtDC0MLAwtDC0NDwwRDSsMEQwQDBANEAwQDBEMEAwQDBEMEAwQDRAMEAwQDRAMEAwRDBAMLQwQDBANLAwtDC0MEAwQDBEMLA0QDBAMLQwtDBAMEA0QDBAMEQwQDBAMEQwQDBAMEQwQDBANEAwQDC0MEAwtDBANEAwQDBEMEAwQDBEMEAwQDRAMEAwQDRAMEAwRDBAMEAwtDC0MEAwRDBAMEAwRDBAMEA0QDBAMEQwsDC0NDwwRDBAMEA0QDBAMEQwQDBAMEQwQDBANEAwQDBANEAwQDBEMEAwQDBEMEAwQDSwMLQwQDBEMEAwQDRAMEAwRDBAMEAwRDBAMEAwRDBAMEA0QDC0MLAwRDBAMEA0QDCwNEAwADQUAAAAAAAAAAA==
  #     #   command_off: JgBQAg0PDBANEA4ODg4OAANEcTkOKw4ODg8ODg4rDg4ODw4ODg4OKw4ODisOKw4ODisOKw4rDioMLQ4ODg8MLQ4ODg4MEQwQDg4NEAwQDBANEAwQDC0MEA4rDg8ODg4ODisOKw4ODg8ODg4ODg8ODg4ODg8ODg4PDg4ODg4PDg4ODg4PDioPKg4rDg4OKw4ODyoOKw4ABHpvOwwtDBAMEQwQDC0MEAwQDRAMEAwtDBAMLQwtDBAMLQwtDCwNKw0tDBAMEQwsDRAMEA4ODRAMEA4PDQ8ODg4PDg4ODg4rDg8ODg4ODg8OKg4PDg4ODw4qDg8OKg8qDisODg4rDg4PDg4ODg8ODg4ODg8OKg8ODg4OKw4ODg8OKg8qDgAEenE5DisODg4PDg4OKw4ODg8ODg4ODisODg8qDisODg4rDisOKw4qDisODg4PDisODg4ODg8ODg4ODg8ODg4PDg4ODg4PDg4ODg4PDg4ODw4ODg4ODw4ODg4OKw4rDisODg4ODg8ODg4rDg4OKw4rDg4ODg4PDg4ODw4ODg4ODw4ODg8NDwwQDg8ODg4ODSwODg0sDBENDwwQDg8ODgwQDg8MEAwRDBAMEA0QDBAMEA0QDBAMEQwsDSwMEA0QDBAMEQwQDBANEAwQDBANEAwtDCwNEAwQDBANEAwQDBEMEAwQDRAMEAwRDBAMEAwRDBAMEAwRDBAMEA0QDBANEAwQDC0MLA0QDBAMEQwQDBAMEQwQDBANEAwQDBEMEAwQDBEMEAwQDRAMEAwtDBAMEQwQDC0MEAwADQUAAAAAAAAAAA==
  #     bedroom_tv:
  #       friendly_name: TV
  #       command_on: JgBIAAABJZcQFRAVEBUQFREVEBUQORAVETkQOhA5EDoQORE5EBUQOhAVEDkRFRAVEDoQFRAVEBUQOhAVEDkRORAVEDoQORA6EAANBQ==
  #       command_off: JgBIAAABJZcQFRAVEBUQFREVEBUQORAVETkQOhA5EDoQORE5EBUQOhAVEDkRFRAVEDoQFRAVEBUQOhAVEDkRORAVEDoQORA6EAANBQ==
  #     bedroom_speaker:
  #       friendly_name: Speaker
  #       command_on: JgBQAAABJpYQFBAUEBUQFBAUEBUQORAVEDkQOhA5EDoQORE5EBQRORAUEBUQFBAUEDoQFBAVEBQQORE5EDoQOQ8WDzoPOw86EAAF2AABJk0QAA0FAAAAAAAAAAA=
  #       command_off: JgBQAAABJpYQFBAUEBUQFBAUEBUQORAVEDkQOhA5EDoQORE5EBQRORAUEBUQFBAUEDoQFBAVEBQQORE5EDoQOQ8WDzoPOw86EAAF2AABJk0QAA0FAAAAAAAAAAA=
  # - platform: rest
  #   resource: http://nodemcu.middle.earth/ac
  #   name: Downstairs AC
  # - platform: command_line
  #   switches:
  #     bedroom_light:
  #       command_on: flux_led -1 smart_light.middle.earth
  #       command_off: flux_led -0 smart_light.middle.earth

fastdotcom:
  scan_interval:
    hours: 6

smartir:

timer:
  tv_sleep_timer:
  manual_bedroom_light:
    duration: "01:00:00"

climate:
  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac
    device_code: 1101
    controller_data: blackbean1
    # delay: 1 # add a bit of delay between commands, 2nd command seems to be missed sometimes
    #smart IR only supports broadlink on this AC
    # no yaml no more
  # - platform: mqtt
  #   name: Downstairs AC
  #   unique_id: downstairs_ac
  #   fan_mode_command_topic: nodemcu/ac/fan
  #   mode_command_topic: nodemcu/ac/mode
  #   temperature_command_topic: nodemcu/ac/temperature
  #   power_command_topic: nodemcu/ac/power
  #   swing_mode_command_topic: nodemcu/ac/swing
  #   precision: 1.0
  #   min_temp: 18
  #   max_temp: 26
  #   modes: ["cool", "fan_only", "off"]
  #   fan_modes: [1, 2, 3, 4, 5, "auto"]

# not working, removing to remove errors
# domain names and mac addresses might need to change.
# Also owntracks seems broken as well.
# device_tracker:
#   - platform: ping
#     consider_home: 300 # 5 min
#     hosts:
#       anu: anu_pixel4a
#       kt: mi9tpro.middle.earth
#   # - platform: nmap_tracker
#   #   hosts:
#   #     - Redmi4X-Redmi
#   #     - mia2lite

input_boolean:
  we_are_in_bed:
    name: We are in bed at night
    icon: mdi:bed-empty
  we_are_going_to_bedroom:
    name: We are headed to the bedroom
    icon: mdi:stairs

light:
  # - platform: switch
  #   name: Bedroom Light
  #   entity_id: switch.bedroom_light

  # Yaml not supported any longer for flux_led.. gonna leave it here in protest.. 
  # this stopped working. Auto discovered light has a different name, need to change its entity id to match light.bedroom_light\
  # cant discover smart_light.. not sure why..
 # - platform: flux_led
 #   devices:
 #     smart_light.middle.earth:
 #       name: Bedroom Light
  - platform: group
    name: Bedroom Light
    entities:
      - light.bulb_rgbw_cfc9e
group:
  all_people:
    name: Both of us
    entities:
      - person.anu
      - person.kt
  bedroom:
    name: Bedroom
    entities:
      # - switch.bedroom_ac
      - light.bedroom_light
      - switch.bedroom_tv
      - switch.bedroom_speaker
  # downstairs:
  #   name: Downstairs
  #   entities:
  #     - switch.downstairs_ac

mobile_app:

telegram_bot:
  - platform: broadcast
    api_key: {{ telegram_bot_api_key }}
    allowed_chat_ids:
      - {{telegram_chat_id}}

notify:
  # not working
  # - name: pushbullet
  #   platform: pushbullet
  #   api_key: {{ pushbullet_access_token }}
  - platform: telegram
    name: telegram
    chat_id: {{telegram_chat_id}}

# Another piece that cant be configured in yaml...
mqtt:
  # broker: localhost
  # port: 1883

owntracks:

binary_sensor:
  - platform: ping
    name: Nodemcu
    host: nodemcu.middle.earth
    scan_interval: 60
    count: 2
  - platform: ping
    name: Blackbean
    host: blackbean1.middle.earth
    scan_interval: 60
    count: 2
  - platform: ping
    name: Smart Light
    host: smart_light.middle.earth
    scan_interval: 60
    count: 2
  - platform: ping
    name: D1 Mini
    host: d1_mini.middle.earth
    scan_interval: 60
    count: 2
  - platform: ping
    name: Esp32
    host: esp32.middle.earth
    scan_interval: 60
    count: 2

person:
  - name: Anu
    id: anu
    device_trackers:
      - device_tracker.wionacmx_pixel4a
      - device_tracker.anu
  - name: Kt
    id: kt
    device_trackers:
      - device_tracker.wionacmx_mia2lite
      - device_tracker.kt
zone:
  # This will override the default home zone
  - name: Home
    latitude: {{ home_lat }}
    longitude: {{ home_long }}
    radius: 400
    icon: mdi:home

# group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

lovelace:
  mode: yaml
