title: Gondor
views:
  - badges:
      # - entity: binary_sensor.blackbean
      - entity: binary_sensor.nodemcu
      - entity: binary_sensor.esp32
      - entity: binary_sensor.d1_mini
      - entity: binary_sensor.smart_light
      - entity: person.anu
      - entity: person.kt
      - entity: sensor.fast_com_download
      - entity: sensor.load_1m
      - entity: sensor.processor_use
      - entity: sensor.processor_temperature
      - entity: sensor.memory_use_percent
      # - entity: sensor.disk_use_percent_archive
      - entity: sensor.disk_use_percent_chest
      - entity: sensor.openweathermap_condition
      - entity: sensor.openweathermap_temperature
      - entity: sensor.bedroom_movement
      - entity: timer.manual_bedroom_light
      - entity: sensor.home_assistant_v2_db_size
      - entity: sensor.bedroom_eco2_value
      - entity: sensor.bedroom_total_volatile_organic_compound
    cards:
      - type: weather-forecast
        entity: weather.openweathermap
      - type: entity
        entity: sensor.date_time
      - type: glance
        title: Anu & Me
        entities:
          - device_tracker.wionacmx_pixel4a
          - device_tracker.anu
          - device_tracker.wionacmx_mia2lite
          - device_tracker.kt
          - person.kt
          - person.anu
      # - entity: climate.bedroom_ac
      #   type: thermostat
      # - entity: climate.downstairs_ac
      #   type: thermostat
      # - entities:
      #     - entity: input_boolean.we_are_going_to_bedroom
      #     - entity: input_boolean.we_are_in_bed
      #   title: Input boolean
      #   type: entities
      # - entities:
      #     - switch.bedroom_tv
      #     - switch.bedroom_speaker
      #   title: Bedroom
      #   type: entities
      # - entities:
      #     - switch.bedroom_light
      #   title: Switch
      #   type: entities
      - type: light
        entity: light.bedroom_light

      - entities:
          - light.bedroom_night_light
          - light.bedroom_light
        title: Light
        type: entities
      - entities:
          - entity: sensor.a_temperature
          - entity: sensor.c_temperature
          - entity: sensor.b_temperature
          - entity: sensor.d_temperature
          - entity: sensor.living_room_temperature
          - entity: sensor.bed_room_temperature
        type: glance
        title: Temperature
      - entities:
          - entity: sensor.a_humidity
          - entity: sensor.c_humidity
          - entity: sensor.b_humidity
          - entity: sensor.d_humidity
          - entity: sensor.living_room_humidity
          - entity: sensor.bed_room_humidity
        type: glance
        title: Humidity
      - entities:
          - entity: sensor.a_battery_level
          - entity: sensor.c_battery_level
          - entity: sensor.b_battery_level
          - entity: sensor.d_battery_level
        type: glance
        title: Thermometer Battery
      # - type: media-control
      #   entity: media_player.bedroom_tv
      # - entities:
      #     - script.downstairs_ac
      #     - script.toggle_tv
      #   title: Script
      #   type: entities
      # this version of HA doesnt have it
      # - type: logbook
      #   entities:
      #     - switch.bedroom_tv
      #     - switch.bedroom_speaker
      #     - climate.bedroom_ac
      #     - climate.downstairs_ac
      #     - person.kt
      #     - person.anu
      #     - device_tracker.wionacmx_pixel4a
      #     - device_tracker.anu
      #     - device_tracker.wionacmx_mia2lite
      #     - device_tracker.kt
      #   hours_to_show: 24
    panel: false
    path: default_view
    title: Home
