title: Gondor
views:
  - badges:
      - entity: binary_sensor.blackbean
      - entity: binary_sensor.nodemcu
      - entity: binary_sensor.smart_light
      - entity: person.anu
      - entity: person.kt
      - entity: sensor.fast_com_download
    cards:
      - type: glance
        title: Anu & Me
        entities:
          - device_tracker.wionacmx_pixel4a
          - device_tracker.anu
          - device_tracker.wionacmx_mia2lite
          - device_tracker.kt
          - person.kt
          - person.anu
      - entity: climate.bedroom_ac
        type: thermostat
      - entity: climate.downstairs_ac
        type: thermostat
      - entities:
          - entity: input_boolean.we_are_going_to_bedroom
          - entity: input_boolean.we_are_in_bed
        title: Input boolean
        type: entities
      - entities:
          - switch.bedroom_tv
          - switch.bedroom_speaker
        title: Bedroom
        type: entities
      - entities:
          - switch.bedroom_light
        title: Switch
        type: entities
      - entities:
          - script.downstairs_ac
          - script.notify_mqtt
          - script.toggle_tv
        title: Script
        type: entities
      - type: logbook
        entities:
          - switch.bedroom_tv
          - switch.bedroom_speaker
          - climate.bedroom_ac
          - climate.downstairs_ac
          - person.kt
          - person.anu
          - device_tracker.wionacmx_pixel4a
          - device_tracker.anu
          - device_tracker.wionacmx_mia2lite
          - device_tracker.kt
        hours_to_show: 24
    panel: false
    path: default_view
    title: Home
