---
- name: setup things specific to the laptop
  hosts: localhost
  become: yes
  tasks:
    - name: add user to input group
      user:
        groups:
          - input
        name: '{{ansible_user_id}}'
        # if not user is removed from all other groups, including the one that gives root access
        append: yes  
    - name: Install libinput dependancies
      apt:
        name:
          - xdotool
          - wmctrl
          - libinput-tools
    - name: Download source code
      become: no
      git:
        repo: git@github.com:bulletmark/libinput-gestures.git
        dest: /tmp/libinput-gestures
    - name: Copy config file
      become: no
      file:
        src: ../dotfiles/libinput-gestures.conf
        path: ~/.config/libinput-gestures.conf
        state: link
    - name: Run install
      shell:
        chdir: /tmp/libinput-gestures/
        cmd: ./libinput-gestures-setup install
    - name: Auto start libinput-gestures
      command: libinput-gestures-setup autostart
      become: no
    - name: Start libinput gestures
      command: libinput-gestures-setup start
      become: no
    - name: Add tmp folder and swap file to fstab
      lineinfile: 
        path: /etc/fstab
        line: '{{item}}'
      with_items:
        -  /home/tmp  /tmp  none  defaults,bind  0  0
        -  /home/11gig.swap    none    swap    sw    0    0
      notify:
        - Ask to restart

  handlers:
    - name: Ask to restart
      debug:
        msg: Restart the laptop to let changes take effect
