---
- hosts: localhost
  connection: local
  tasks:

  - name: Install zsh
    apt: pkg=zsh state=present
    when: ansible_os_family != "Darwin"
    with_items: [zsh, curl]
    sudo: yes

  - name: Install zsh (osx)
    homebrew: name=zsh state=present
    when: ansible_os_family == "Darwin"

#http://zanshin.net/2013/09/03/how-to-use-homebrew-zsh-instead-of-max-os-x-default/
  - name: Add to /etc/shells
    lineinfile: dest=/etc/shells line=/usr/local/bin/zsh
    sudo: yes  #needs --ask-sudo-pass
    when: ansible_os_family == "Darwin"

  - name: Change shell to homebrew version
    command: chsh -s /usr/local/bin/zsh
    when: ansible_os_family == "Darwin"

  - name: Install Oh-My-Zsh
    shell: curl -L http://install.ohmyz.sh | sh creates=~/.oh-my-zsh

  - name: Link zshrc
    file: src=dotfiles/zsh/zshrc dest=~/.zshrc state=link force=yes # force cuz oh-my-zsh creates one

  - name: Link up custom themes folder
    file: src=~/dotfiles/zsh/themes dest=~/.oh-my-zsh/custom/themes state=link force=yes

  #TODO improve this step
  - name: Update submodule
    command: git submodule update --init

#  - name: Install powerline fonts
#    shell: ~/dotfiles/powerline/fonts/install.sh

  - name: Grab plugins
    shell: ls ~/dotfiles/zsh/plugins/
    register: plugins

  - name: Link up custom plugins
    file: src=~/dotfiles/zsh/plugins/{{item}} dest=~/.oh-my-zsh/custom/plugins/{{item}} state=link force=yes
    with_items: plugins.stdout_lines
