# Run with
# ansible-playbook setup_dotfiles.yml -i inventory.yml
---
- hosts: localhost
  tasks:

  - name: Install nice CLI packages on Debian systems
    apt: pkg={{item}} state=present
    with_items:
      - htop
      - byobu
      - git
      - vim
      - ncdu
      - guake
    when: ansible_os_family != 'Darwin'
    sudo: yes

    # unnecessary since need to install homebrew to install ansible in the first place..
  # - name: Install Homebrew on osx
  #   shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" creates=/usr/local/Cellar

  - name: Install nice CLI packages on OSX systems
    homebrew: pkg={{item}} state=present
    with_items:
      - htop
      - byobu
      - reattach-to-user-namespace # needed for http://superuser.com/questions/834525/unable-to-launch-application-in-tmux
      - git
      - vim
      - ncdu
      - wget
      - direnv
    when: ansible_os_family == 'Darwin'

  - name: Checkout/update dotfiles on target machine
    git: repo=https://github.com/ktaragorn/dotfiles.git dest=~/dotfiles force=no
    # Assuming localhost is always updated
    when: ansible_connection != "local"

  - name: Ensure bash files exist
    command: touch ~/.{{item}} creates=~/.{{item}}
    with_items:
    - bashrc
    - bash_profile

  - name: Ensure bash_profile sources bashrc
    lineinfile: dest=~/.bash_profile line=". ~/.bashrc"

  - name: Add source line for bashrc
    lineinfile: dest=~/.bashrc line=". ~/dotfiles/bashrc.d/source_all"

  - name: Link the basic dotfiles which are linked to .file in home
    file: src=dotfiles/{{item}} dest=~/.{{item}} state=link
    with_items:
      - vimrc
      - ngrok
      - rdebugrc
      - gitconfig
      - pryrc
      - gemrc
      - bcrc
      - Xmodmap # only used in linux though

  - name: Link inputrc
    file: src=dotfiles/bashrc.d/inputrc dest=~/.inputrc state=link

  #https://github.com/Russell91/sshrc
  - name: Link sshrc file and folder
    file: src=dotfiles/sshrc/{{item}} dest=~/.{{item}} state=link
    with_items:
      - sshrc
      - sshrc.d

  - name: Link tmux.conf in debian systems
    file: src=~/dotfiles/tmux.conf dest=~/.config/byobu/.tmux.conf state=link force=yes
    when: ansible_os_family != 'Darwin'

  - name: Link tmux.conf in osx systems
    file: src=~/dotfiles/tmux.conf dest=~/.byobu/.tmux.conf state=link force=yes
    when: ansible_os_family == 'Darwin'


    # TODO RVM? Brew, tmuxinator tmux config
