# Run with
# ansible-playbook setup_dotfiles.yml -i inventory.yml
---
- hosts: localhost
  tasks:
    - name: Add byobu PPA on debian machines
      apt_repository: repo='ppa:byobu/ppa' update_cache=yes
      when: ansible_os_family != 'Darwin'
      become: yes

    - name: Install nice CLI packages on Debian systems
      apt:
        pkg:
          - htop
          - byobu
          - git
          - vim
          - ncdu
          - guake
          - git-gui
          - net-tools
          - gitg
          - bat # cat replacement
          #- broot # a better tree
          #- exa # cd replacement
          #- tokei # cloc replacement
        state: present

      when: ansible_os_family != 'Darwin'
      become: yes

    - name: Install nice CLI packages on OSX systems
      homebrew:
        state: present
        pkg:
          - htop
          - byobu
          - reattach-to-user-namespace # needed for http://superuser.com/questions/834525/unable-to-launch-application-in-tmux
          - git
          - vim
          - ncdu
          - wget
          - direnv
          - bat # cat replacement
          - broot # a better tree
          - exa # cd replacement
          - tokei # cloc replacement
      when: ansible_os_family == 'Darwin'

    # for FB need to use non standard prefix
    - name: Find brew prefix
      shell: brew --prefix
      register: brew_prefix
      when: ansible_os_family == 'Darwin'

    #http://superuser.com/a/373448/160502
    - name: Fix htop for osx
      file: name={{brew_prefix.stdout}}/bin/htop mode=6555 owner=root follow=yes
      become: yes
      when: ansible_os_family == 'Darwin'

      #  - name: Install brew cask
      #homebrew: pkg=caskroom/cask/brew-cask
      #when: ansible_os_family == 'Darwin'
    - name: Install casks
      when: ansible_os_family == 'Darwin'
      ignore_errors: True
      homebrew_cask:
        name:
          - Alfred 4 # disable spotlight, set alfreds keybinds
          - rowanj-gitx
          - iterm2
          - caffeine
          - itsycal # E MMM d h:mm a
          - karabiner-elements
          - sensiblesidebuttons
          - firefox
          - google-chrome

    - name: Add casks to login
      when: ansible_os_family == 'Darwin'
      tags: login
      shell: osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/{{item}}.app", hidden:false}'
      with_items:
        - Itsycal
        - iTerm
        - Caffeine
        - Alfred 4
        - SensibleSideButtons

    - name: Checkout/update dotfiles on target machine
      git: repo=https://github.com/ktaragorn/dotfiles.git dest=~/dotfiles force=no
      # Assuming localhost is always updated
      when: ansible_connection != "local"

    - name: Create .ssh folder
      file:
        dest: ~/.ssh
        state: directory

    - name: Copy pine SSH key
      copy:
        mode: 0600
        src: pine/files/pine.key
        dest: ~/.ssh/pine.key

    - name: Pine ssh config section
      blockinfile:
        create: yes
        path: ~/.ssh/config
        block: |
          host pine
            hostname black-gate.privatedns.org
            user ubuntu
            port 22
            identityfile ~/.ssh/pine.key

    - name: Ensure bash files exist
      file:
        state: touch
        path: ~/.{{item}}
      with_items:
        - bashrc
        - bash_profile

    - name: Ensure bash_profile sources bashrc
      lineinfile: dest=~/.bash_profile line=". ~/.bashrc"

    - name: Add source line for bashrc
      lineinfile: dest=~/.bashrc line=". ~/dotfiles/bashrc.d/source_all"

    - name: Link the basic dotfiles which are linked to .file in home
      file: src=dotfiles/{{item}} dest=~/.{{item}} state=link
      with_items:
        - vimrc
        - ngrok
        - rdebugrc
        - gitconfig
        - pryrc
        - gemrc
        - bcrc
        - Xmodmap # only used in linux though
        - tmuxinator
        - asdfrc

    - name: Install asdf version 0.7.3
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf
        version: v0.7.3

    - name: Install ruby and node plugins
      shell: asdf plugin-add {{item}}
      args:
        creates: ~/.asdf/plugins/{{item}}
      with_items:
        - ruby
        - nodejs

    - name: Link inputrc
      file: src=dotfiles/bashrc.d/inputrc dest=~/.inputrc state=link

    #https://github.com/Russell91/sshrc
    - name: Link sshrc file and folder
      file: src=dotfiles/sshrc/{{item}} dest=~/.{{item}} state=link
      with_items:
        - sshrc
        - sshrc.d

    #https://askubuntu.com/questions/7190/why-wont-my-xmodmap-file-load-on-login
    - name: Autostart Xmodmap in linux
      when: ansible_os_family != 'Darwin' #gnome only??
      file:
        dest: ~/.config/autostart/
        state: directory

    - name: Autostart Xmodmap and guake in linux
      when: ansible_os_family != 'Darwin' #gnome only??
      file: src=~/dotfiles/{{item}}.desktop dest=~/.config/autostart/{{item}}.desktop state=link force=yes mode=u+x
      with_items:
        - my-xmodmap
        - guake

    - name: Create byobu config folder
      file: dest=~/.config/byobu state=directory
      when: ansible_os_family != 'Darwin'

    - name: Link tmux.conf in debian systems
      file: src=~/dotfiles/tmux.conf dest=~/.config/byobu/.tmux.conf state=link force=yes
      when: ansible_os_family != 'Darwin'

    - name: Create byobu folder in case it doesnt exist
      file: path=~/.byobu state=directory
      when: ansible_os_family == 'Darwin'

    - name: Link tmux.conf in osx systems
      file: src=~/dotfiles/tmux.conf dest=~/.byobu/.tmux.conf state=link force=yes
      when: ansible_os_family == 'Darwin'

    - name: Link karabiner.json in osx systems
      file: src=~/dotfiles/karabiner/karabiner.json dest=~/.config/karabiner/karabiner.json state=link force=yes
      when: ansible_os_family == 'Darwin'

      # From http://lifehacker.com/5826055/make-your-keyboard-keys-repeat-properly-when-held-down-in-mac-os-x-lion
    - name: Fix key repeat on osx
      command: defaults write -g ApplePressAndHoldEnabled -bool false
      when: ansible_os_family == 'Darwin'
