---
- name: Install Sublime text
  hosts: localhost
  tasks:
    - include: sublime/osx.yml
      when: ansible_os_family == 'Darwin'
    - include: sublime/deb.yml
      when: ansible_os_family != 'Darwin'

- name: Setup user preferences folder
  hosts: localhost
  tags: link
  vars: #potentially can clean this up by moving this to files and loading with `include_vars`
    all_paths:
      osx:
        src: ~/dotfiles/Sublime Text 3/Packages/User
        dest: ~/Library/Application Support/Sublime Text 3/Packages/User
      linux:
        src: ~/dotfiles/Sublime Text 3/Packages/User
        dest: ~/.config/sublime-text-3/Packages/User
    os: '{{(ansible_os_family == "Darwin") | ternary("osx", "linux")}}'
    paths: '{{all_paths[os]}}'
  tasks:
    - name: Create user Folder
      file: dest={{paths.dest}} state=directory
    - name: Link user folder
      file: state=link src="{{paths.src}}" dest="{{paths.dest}}" force=yes
      when: ansible_os_family == 'Darwin'
