---
- name: Install pip and other tools required
  apt:
    pkg:
      - python3-pip
      - htop
      - git
      - jq
      - unattended-upgrades
      - ncdu
      - lm-sensors
      - pkg-config
    update_cache: yes
- name: Add .local/bin to PATH for regular user
  become: no
  lineinfile: dest=~/.bashrc line="export PATH=$PATH:.local/bin/" create=yes
- name: Install locate if needed
  apt: pkg=locate state=present
  notify: updatedb
- name: set timezone to {{timezone}}
  # timezone: # doesnt work..
  #   name: '{{timezone}}'
  command: timedatectl set-timezone {{timezone}}
- name: Download z.sh
  get_url: url=https://raw.githubusercontent.com/rupa/z/master/z.sh dest=~/z.sh
  become: no
- name: Activate z.sh
  lineinfile: dest=~/.bashrc line=". ~/z.sh" create=yes
  become: no
- name: Create .ssh directory
  file: dest=/home/{{user_name}}/.ssh state=directory
  become: no
- name: setup ssh keys - VM, Office, Putty, Phone Juicessh, WSL, linux laptop
  copy: src=../pine/files/authorized_keys dest=~/.ssh/authorized_keys
  become: no
- name: Allow TCP forwarding to allow remote access
  lineinfile: dest=/etc/ssh/sshd_config regexp="^AllowTcpForwarding" line="AllowTcpForwarding yes" state=present
  notify: Restart ssh
- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: Restart ssh
- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: Restart ssh
- name: setup no password sudo
  lineinfile: "dest=/etc/sudoers state=present line='{{user_name}}    ALL=NOPASSWD: ALL'"
- name: Point DNS to router
  copy:
    src: ../pine/files/resolv.conf
    dest: /etc/resolv.conf
- name: Cron to curl privatedns
  cron:
    name: "Update dyndns for {{item.name}}"
    user: ubuntu
    special_time: hourly
    job: curl -s http://freedns.afraid.org/dynamic/update.php?{{item.token}}/ >> /tmp/freedns_black-gate_privatedns_org.log 2>/dev/null
  with_items: "{{ freedns_tokens }}"
