#!/bin/bash
/home/ubuntu/pushbullet "[Monit-$MONIT_HOST] $MONIT_SERVICE - $MONIT_EVENT" "$MONIT_DESCRIPTION"
/home/ubuntu/telegram "[Monit-$MONIT_HOST] $MONIT_SERVICE - $MONIT_EVENT - $MONIT_DESCRIPTION"
docker exec mqtt mosquitto_pub -q 1 -t notify/monit/$MONIT_SERVICE -m "$MONIT_EVENT - $MONIT_DESCRIPTION"